### ISSUE TITLE
Replies forward previously forwarded emails

### ISSUE THREAD

**Issue by jbranch-fenix** [emreberge/gmail-email-forwarding#1]
My company use this script to forward emails from one inbox to another. We are experiencing an issue where if someone responds back to an email that has already been forwarded then when the forwarder goes to forward the new email it will also forward the older emails, including those that have already been forwarded and their forwarded copies. This increases exponentially as more replies are received, a recent email with 12 responses has ended up with 204 responses due to the forwarding (I believe Google hits a limit at 100 emails, and the curve resets after that). Is there any way to possibly exclude emails that have already been forwarded, or at least any emails that have a sender that matches the fromAddress?

**Comment by emreberge** [comment]
Hi J. Branch,

I see the issue. Gmail handles labels on thread level (and not individual emails), which is the mecanizm this script uses to mark a message (in reality all messages in a thread) to be forwarded. So there isn't a robust fix that I can quickly think of unfortunately.

**A quick fix you can try would be to**
* Find the index of the last message that is from `fromAddress` to `forwardingAddress`
* And then only forward any messages after this index.

Feel free to try this, and share the code if it works without errors!

But for your use case, you could potentially skip the script all together, and simply use the [email forwarding option already available at gmail filter level](https://support.google.com/mail/answer/10957?hl=en#zippy=%2Cyour-filters-are-forwarding-some-of-your-mail-notice%2Cforward-emails-from-another-email-service-to-gmail%2Conly-forward-certain-kinds-of-messages).

**Comment by jbranch-fenix** [comment]
Hi Emre

Unfortunately Gmail's forwarding option didn't work for us, as we need the address that the email is coming from to change. The CRM Zendesk doesn't like receiving emails from an email already set up as a system user, so we needed internal emails to seem like they're coming from somewhere else.

I'm not terribly sure how I would apply that quick fix, but a quick change that worked on our end was to disable the conversation view and update the label applying filter to block emails that have already been sent. This stops the emails from threading, and while they duplicate in the original inbox, those duplicates will not be forwarded on.

**Comment by emreberge** [comment]
That is  good solution! Well done!
